### ISSUE TITLE
Inconsistent capitalization of nouns

### ISSUE THREAD

**Issue by chrislo27** [blerchy/LucidMaths#7]
C'mon maty you can do better than this

![buleah](http://i.imgur.com/euCTMLC.png)

**Comment by blerchy** [comment]
Does this look better?

![screen shot 2015-07-21 at 1 04 41 pm](https://cloud.githubusercontent.com/assets/2555355/8799686/31eac826-2fac-11e5-9a67-819dd26ea754.png)
![screen shot 2015-07-21 at 1 04 49 pm](https://cloud.githubusercontent.com/assets/2555355/8799687/31f59698-2fac-11e5-9658-0eb1bb619b86.png)

**Comment by chrislo27** [comment]
Good enough.

**Comment by blerchy** [comment]
Then that settles it.
